// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.0
// source: api/proto/pathfinder-service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PathfinderService_GetPath_FullMethodName = "/pathfinder.PathfinderService/GetPath"
)

// PathfinderServiceClient is the client API for PathfinderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PathfinderServiceClient interface {
	GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error)
}

type pathfinderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPathfinderServiceClient(cc grpc.ClientConnInterface) PathfinderServiceClient {
	return &pathfinderServiceClient{cc}
}

func (c *pathfinderServiceClient) GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error) {
	out := new(GetPathResponse)
	err := c.cc.Invoke(ctx, PathfinderService_GetPath_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathfinderServiceServer is the server API for PathfinderService service.
// All implementations must embed UnimplementedPathfinderServiceServer
// for forward compatibility
type PathfinderServiceServer interface {
	GetPath(context.Context, *GetPathRequest) (*GetPathResponse, error)
	mustEmbedUnimplementedPathfinderServiceServer()
}

// UnimplementedPathfinderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPathfinderServiceServer struct {
}

func (UnimplementedPathfinderServiceServer) GetPath(context.Context, *GetPathRequest) (*GetPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPath not implemented")
}
func (UnimplementedPathfinderServiceServer) mustEmbedUnimplementedPathfinderServiceServer() {}

// UnsafePathfinderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PathfinderServiceServer will
// result in compilation errors.
type UnsafePathfinderServiceServer interface {
	mustEmbedUnimplementedPathfinderServiceServer()
}

func RegisterPathfinderServiceServer(s grpc.ServiceRegistrar, srv PathfinderServiceServer) {
	s.RegisterService(&PathfinderService_ServiceDesc, srv)
}

func _PathfinderService_GetPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathfinderServiceServer).GetPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathfinderService_GetPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathfinderServiceServer).GetPath(ctx, req.(*GetPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PathfinderService_ServiceDesc is the grpc.ServiceDesc for PathfinderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PathfinderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pathfinder.PathfinderService",
	HandlerType: (*PathfinderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPath",
			Handler:    _PathfinderService_GetPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/pathfinder-service.proto",
}
